### PR TITLE
UI prototype.

### PR DESCRIPTION
**Pull request by escalonn**

### CODE REVIEW

**Comment by escalonn** [comment]
@newlandp this does not build. fix

**Comment by newlandp** [comment]
working on it. docker specific thing

**Comment by escalonn** [comment]
doesn't build outside docker for me either. same error. (`Cannot find module '@angular/animations'.`, `Cannot find module '@angular/animations/browser'.`
missing stuff from package.json?
try deleting your node_modules and `npm install` again, you should reproduce the error

**Comment by newlandp** [comment]
was working on it with andrew and sounds like it wasn't doing both npm install's in the different folders?

**Pull request merged**
